#!/bin/bash

set -e
set -u
set -o pipefail

DIST=${1:?Specify the distrubution name}
PLATFORM=${2:-amd64}

BASENAME=shardbyte/shard-minideb

if [ -n "${DOCKER_PASSWORD:-}" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
fi

push() {
    local dist="$1"
    docker push "${BASENAME}:${dist}"
}

push "$DIST-${PLATFORM}"
