name: CI

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
env:
  BASENAME: shardbyte/shard-minideb
  LATEST: bookworm
jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    name: Shellcheck
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y shellcheck
      - name: Verify scripts with shellcheck
        run: |
          bash shellcheck

  build_multiarch:
    runs-on: ubuntu-22.04
    needs: [ shellcheck ]
    strategy:
      matrix:
        dist: [bullseye, bookworm]
        arch: [amd64, arm64]

    name: Build ${{ matrix.dist }} on ${{ matrix.arch }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Use local build action
        id: build
        uses: ./.github/actions/build
        with:
          dist: "${{ matrix.dist }}"
          platform: "${{ matrix.arch }}"
          is_latest: ${{ matrix.dist == env.LATEST }}
      - name: Push
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          bash pushone "${{ matrix.dist }}" "${{ matrix.arch }}"
          if ${{ matrix.dist == env.LATEST }} ; then
             bash pushone "latest" "${{ matrix.arch }}"
          fi

  deploy_manifests:
    runs-on: ubuntu-22.04
    needs: [ build_multiarch ]
    if: github.ref == 'refs/heads/main'
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Push Manifests
        run: |
          DISTS="bullseye bookworm latest" bash pushmanifest
